remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Tile Galore"
description: "Tile Matching Game that randomly generates tiles for users to memorize and match"
author:
  name: "Victor Perez"

# Do not change the following line.
  copyright: true
